services:
  database:
    image: postgres:17
    container_name: weather_data_db
    environment:
      - POSTGRES_USER=allan
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=weather_data
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres/data:/var/lib/postgresql/data 
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my-network
      
  airflow:
    image: apache/airflow:3.0.0
    container_name: airflow_container
    ports:
     - "8000:8080"
    environment:
      AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@database:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api_request:/opt/airflow/api_request
    depends_on:
      - database
    networks:
      - my-network
    command: >
      bash -c "airflow db migrate && airflow standalone"
      
  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/my_project:/usr/app
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
    working_dir: /usr/app
    depends_on:
      - database
    networks:
      - my-network
    command: run
networks:
  my-network:
   driver: bridge